Attribute VB_Name = "DocConsts"
Public Const app1$ = "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?><Properties xmlns=""http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"" xmlns:vt=""http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes""><Template>"
Public Const app2$ = _
"</Template><TotalTime>0</TotalTime><Pages>22</Pages><Words>10553</Words><Characters>66490" & _
"</Characters><Application>Microsoft Office Word</Application><DocSecurity>0</DocSecurity><Lines>554" & _
"</Lines><Paragraphs>153</Paragraphs><ScaleCrop>false</ScaleCrop><HeadingPairs><vt:vector size=""2"" baseType=""variant""><vt:variant><vt:lpstr>" & _
"Titel</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts>" & _
"<vt:vector size=""1"" baseType=""lpstr""><vt:lpstr>#12</vt:lpstr></vt:vector></TitlesOfParts><Company>Diabetologische Gemeinschaftspraxis Dachau</Company><LinksUpToDate>false</LinksUpToDate><CharactersWithSpaces>76890</CharactersWithSpaces><SharedDoc>false</SharedDoc><HLinks><vt:vector size=""6"" baseType=""variant"">" & _
"<vt:variant><vt:i4>4128804</vt:i4></vt:variant><vt:variant><vt:i4>69686</vt:i4></vt:variant><vt:variant><vt:i4>1025</vt:i4></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant><vt:variant><vt:lpwstr>Unterschrift 2</vt:lpwstr></vt:variant><vt:variant><vt:lpwstr></vt:lpwstr>" & _
"</vt:variant></vt:vector></HLinks><HyperlinksChanged>false</HyperlinksChanged><AppVersion>16.0000</AppVersion></Properties>"

Public Const core1$ = "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>" & _
"<cp:coreProperties xmlns:cp=""http://schemas.openxmlformats.org/package/2006/metadata/core-properties"" xmlns:dc=""http://purl.org/dc/elements/1.1/"" xmlns:dcterms=""http://purl.org/dc/terms/"" xmlns:dcmitype=""http://purl.org/dc/dcmitype/"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""><dc:title>#12</dc:title><dc:subject></dc:subject><dc:creator>"
Public Const core2$ = "</dc:creator><cp:keywords></cp:keywords><dc:description></dc:description><cp:lastModifiedBy>"
Public Const core3$ = "</cp:lastModifiedBy><cp:revision>2</cp:revision><dcterms:created xsi:type=""dcterms:W3CDTF"">"
Public Const core4$ = "</dcterms:created><dcterms:modified xsi:type=""dcterms:W3CDTF"">"
Public Const core5$ = "</dcterms:modified></cp:coreProperties>"

Public Const settings1$ = "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?> " & _
"<Relationships xmlns=""http://schemas.openxmlformats.org/package/2006/relationships"">" & _
"<Relationship Id=""rId1"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/attachedTemplate"" Target=""file:///"
Public Const settings2$ = """ TargetMode=""External""/> </Relationships>"

Public Const kopf0$ = "xmlns:wpc=""http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"" xmlns:cx=""http://schemas.microsoft.com/office/drawing/2014/chartex"" xmlns:cx1=""http://schemas.microsoft.com/office/drawing/2015/9/8/chartex"" xmlns:cx2=""http://schemas.microsoft.com/office/drawing/2015/10/21/chartex"" xmlns:cx3=""http://schemas.microsoft.com/office/drawing/2016/5/9/chartex"" xmlns:cx4=""http://schemas.microsoft.com/office/drawing/2016/5/10/chartex"" xmlns:cx5=""http://schemas.microsoft.com/office/drawing/2016/5/11/chartex"" xmlns:cx6=""http://schemas.microsoft.com/office/drawing/2016/5/12/chartex"" xmlns:cx7" & _
"=""http://schemas.microsoft.com/office/drawing/2016/5/13/chartex"" xmlns:cx8=""http://schemas.microsoft.com/office/drawing/2016/5/14/chartex"" xmlns:mc=""http://schemas.openxmlformats.org/markup-compatibility/2006"" xmlns:aink=""http://schemas.microsoft.com/office/drawing/2016/ink"" xmlns:am3d=""http://schemas.microsoft.com/office/drawing/2017/model3d""" & vbCrLf & _
"xmlns:o=""urn:schemas-microsoft-com:office:office"" xmlns:r=""http://schemas.openxmlformats.org/officeDocument/2006/relationships"" xmlns:m=""http://schemas.openxmlformats.org/officeDocument/2006/math"" xmlns:v=""urn:schemas-microsoft-com:vml"" xmlns:wp14=""http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing"" xmlns:wp=""http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"" xmlns:w10=""urn:schemas-microsoft-com:office:word"" xmlns:w=""http://schemas.openxmlformats.org/wordprocessingml/2006/main"" xmlns:w14=""http://schemas.microsoft.com/office/word/2010/wordml"" xmlns:w15" & _
"=""http://schemas.microsoft.com/office/word/2012/wordml"" xmlns:w16cid=""http://schemas.microsoft.com/office/word/2016/wordml/cid"" xmlns:w16se=""http://schemas.microsoft.com/office/word/2015/wordml/symex"" xmlns:wpg=""http://schemas.microsoft.com/office/word/2010/wordprocessingGroup"" xmlns:wpi=""http://schemas.microsoft.com/office/word/2010/wordprocessingInk"" " & vbCrLf & _
"xmlns:wne=""http://schemas.microsoft.com/office/word/2006/wordml"" xmlns:wps=""http://schemas.microsoft.com/office/word/2010/wordprocessingShape"" mc:Ignorable=""w14 w15 w16se w16cid wp14"">"

Public Const header1$ = "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>" & vbCrLf & "<w:hdr " & kopf0 & "<w:p w:rsidR=""00000000"" w:rsidRDefault="""
Public Const header2$ = """><w:pPr><w:pStyle w:val=""Kopfzeile""/><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t xml:space=""preserve"">Arztbrief zu </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t>"
Public Const header3$ = ", vo</w:t></w:r><w:r><w:t xml:space=""preserve"">m </w:t></w:r><w:r><w:fldChar w:fldCharType=""begin""/></w:r><w:r><w:instrText xml:space=""preserve""> SAVEDATE  \@ ""dd.MM.yy""  \* MERGEFORMAT </w:instrText></w:r><w:r><w:fldChar w:fldCharType=""separate""/></w:r><w:r><w:rPr><w:noProof/></w:rPr><w:t>"
Public Const header4$ = "</w:t></w:r><w:r><w:fldChar w:fldCharType=""end""/></w:r><w:r><w:tab/><w:t>-</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t xml:space=""preserve"">Seite </w:t></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts " & _
"w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:fldChar w:fldCharType=""begin""/></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:instrText xml:space=""preserve""> PAGE </w:instrText></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:fldChar w:fldCharType=""separate""/></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:noProof/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t>17</w:t></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:fldChar w:fldCharType=""end""/></w:r><w:r><w:rPr>" & _
"<w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t>/</w:t></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:fldChar w:fldCharType=""begin""/></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:instrText xml:space=""preserve""> NUMPAGES </w:instrText></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:fldChar w:fldCharType=""separate""/></w:r><w:r><w:rPr><w:rStyle " & _
"w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:noProof/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t>22</w:t></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:fldChar w:fldCharType=""end""/></w:r><w:r><w:rPr><w:rStyle w:val=""Seitenzahl""/><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr><w:t>-</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
Public Const header5$ = """><w:pPr><w:pStyle w:val=""Kopfzeile""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/></w:rPr></w:pPr></w:p></w:hdr>"

Public Const doc1$ = "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>" & vbCrLf & "<w:document ", _
 vors$ = "<w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/>", _
 doc2$ = "<w:b/><w:position w:val=""-6""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/><w:sz w:val=""28""/><w:szCs w:val=""28""/></w:rPr><w:t>D</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/></w:rPr><w:t xml:space=""preserve"">iabetologische </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/><w:sz w:val=""28""/><w:szCs w:val=""28""/></w:rPr><w:t>G</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/></w:rPr><w:t xml:space=""preserve"">emeinschaftspraxis </w:t></w:r></w:p>", _
 doc3$ = "</w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:position w:val=""-6""/></w:rPr><w:t>Dr. Thomas Kothny - Gerald Schade</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>Tel.:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>08131 616380</w:t></w:r></w:p>", _
 doc4$ = "<w:sz w:val=""16""/><w:szCs w:val=""16""/><w:lang w:val=""fr-FR""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:position w:val=""8""/><w:sz w:val=""16""/><w:szCs w:val=""16""/><w:lang w:val=""fr-FR""/></w:rPr><w:t xml:space=""preserve"">Internisten - Diabetologen - Angiologe </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/><w:lang w:val=""fr-FR""/></w:rPr><w:tab/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:lang w:val=""fr-FR""/></w:rPr><w:t>Fax:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:lang w:val=""fr-FR""/></w:rPr><w:tab/><w:t>08131 616381</w:t></w:r></w:p>", _
 doc5$ = "</w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:t>Mittermayerstra�e 13</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>Email:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>diabetologie@dachau-mail.de</w:t></w:r></w:p>", _
 doc6$ = "<w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:t>85221 Dachau</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>Web:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>www.diabdachau.de</w:t></w:r></w:p>", _
 doc7$ = "<w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:leader=""underscore"" w:pos=""9072""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/></w:r></w:p>", _
 doc8$ = "<w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""right"" w:pos=""8789""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:spacing w:before=""120""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:fldChar w:fldCharType=""begin""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:instrText xml:space=""preserve""> CREATEDATE \@ ""dd.MM.yyyy"" \* MERGEFORMAT </w:instrText></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:fldChar w:fldCharType=""separate""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:noProof/></w:rPr><w:t>", _
 doc9$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:fldChar w:fldCharType=""end""/></w:r></w:p>", _
 doc10$ = "<w:pPr><w:spacing w:before=""80""/><w:ind w:firstLine=""709""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr></w:pPr></w:p>", _
 doc11$ = "<w:pPr><w:spacing w:before=""80""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:t>Diabetolog. Gem`praxis</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:sym w:font=""Symbol"" w:char=""F0B7""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:t xml:space=""preserve"">" & _
          " Mittermayerstra�e 13 </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:sym w:font=""Symbol"" w:char=""F0B7""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:t xml:space=""preserve""> 85221 Dachau</w:t></w:r></w:p>", _
 doc12$ = "<w:pPr><w:spacing w:before=""80""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr></w:pPr></w:p>"
 

' <w:p w14:paraId=""528D1A2F"" w14:textId=""77777777"" w:rsidR=""00000000"" w:rsidRDefault=""00C730E7"">

' Public Const doc2$ = "<w:body><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc3$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:position w:val=""-6""/></w:rPr></w:pPr><w:bookmarkStart w:id=""0"" w:name=""_GoBack""/><w:bookmarkEnd w:id=""0""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/><w:sz w:val=""28""/><w:szCs w:val=""28""/></w:rPr><w:t>D</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/></w:rPr><w:t xml:space=""preserve"">iabetologische </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/><w:sz w:val=""28""/><w:szCs " & _
            "w:val=""28""/></w:rPr><w:t>G</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial"" w:cs=""Arial""/><w:b/></w:rPr><w:t xml:space=""preserve"">emeinschaftspraxis </w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc4$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:position w:val=""-6""/></w:rPr><w:t>Dr. Thomas Kothny - Gerald Schade</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>Tel.:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>08131 616380</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc5$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" " & _
            "w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/><w:lang w:val=""fr-FR""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:position w:val=""8""/><w:sz w:val=""16""/><w:szCs w:val=""16""/><w:lang w:val=""fr-FR""/></w:rPr><w:t xml:space=""preserve"">Internisten - Diabetologen  – Angiologe </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/><w:szCs w:val=""16""/><w:lang w:val=""fr-FR""/></w:rPr><w:tab/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:lang w:val=""fr-FR""/></w:rPr><w:t>Fax:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:lang w:val=""fr-FR""/></w:rPr><w:tab/><w:t>08131 616381</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc6$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" " & _
            "w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:t>Mittermayerstraße 13</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>Email:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>diabetologie@dachau-mail.de</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc7$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/><w:tab w:val=""left"" w:pos=""6237""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:t>85221 Dachau</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" " & _
            "w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>Web:</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/><w:t>www.dachau-surf.de/diabetologie</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc8$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""left"" w:leader=""underscore"" w:pos=""9072""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc9$ = """><w:pPr><w:widowControl w:val=""0""/><w:tabs><w:tab w:val=""right"" w:pos=""8789""/></w:tabs><w:autoSpaceDE w:val=""0""/><w:autoSpaceDN w:val=""0""/><w:adjustRightInd w:val=""0""/><w:spacing w:before=""120""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:tab/></w:r><w:r><w:rPr><w:rFonts " & _
" w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:fldChar w:fldCharType=""begin""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:instrText xml:space=""preserve""> CREATEDATE  \@ ""dd.MM.yyyy"" \* MERGEFORMAT </w:instrText></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:fldChar w:fldCharType=""separate""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:noProof/></w:rPr><w:t>"
' Public Const doc10$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/></w:rPr><w:fldChar w:fldCharType=""end""/></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' kommt 2 x vor:
' Public Const doc11$ = """><w:pPr><w:spacing w:before=""80""/><w:ind w:firstLine=""709""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr></w:pPr></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc12$ = """><w:pPr><w:spacing w:before=""80""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:t>Diabetolog. Gem’praxis</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:sym w:font=""Symbol"" w:char=""F0B7""/></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:t xml:space=""preserve""> Mittermayerstraße 13 </w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:sym w:font=""Symbol"" w:char=""F0B7""/" & _
                      "></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:i/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr><w:t xml:space=""preserve""> 85221 Dachau</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc13$ = """><w:pPr><w:spacing w:before=""80""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:iCs/><w:sz w:val=""16""/><w:u w:val=""single""/></w:rPr></w:pPr></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc14$ = """><w:pPr><w:tabs><w:tab w:val=""left"" w:pos=""5387""/></w:tabs><w:spacing w:before=""140""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr></w:pPr><w:bookmarkStart w:id=""1"" w:name=""ha1a""/><w:bookmarkEnd w:id=""1""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t xml:space=""preserve"">"
' Public Const doc15$ = "</w:t></w:r><w:bookmarkStart w:id=""2"" w:name=""ha10a""/><w:bookmarkEnd w:id=""2""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:tab/></w:r><w:bookmarkStart w:id=""3"" w:name=""ha1b""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc16$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t>$1210$</w:t></w:r><w:bookmarkEnd w:id=""3""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t xml:space=""preserve""> </w:t></w:r><w:bookmarkStart w:id=""4"" w:name=""ha10b""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t xml:space=""preserve""> </w:t></w:r><w:bookmarkEnd w:id=""4""/></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc17$ = """><w:pPr><w:tabs><w:tab w:val=""left"" w:pos=""5387""/></w:tabs><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr></w:pPr><w:bookmarkStart w:id=""5"" w:name=""ha2a""/><w:bookmarkEnd w:id=""5""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc18$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:tab/></w:r><w:bookmarkStart w:id=""6"" w:name=""ha2b""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc19$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t>$1203$ $1202$ $1201$</w:t></w:r><w:bookmarkEnd w:id=""6""/></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc20$ = """><w:pPr><w:tabs><w:tab w:val=""left"" w:pos=""5387""/></w:tabs><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr></w:pPr><w:bookmarkStart w:id=""7"" w:name=""ha3a""/><w:bookmarkEnd w:id=""7""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc21$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:tab/></w:r><w:bookmarkStart w:id=""8"" w:name=""ha3b""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc22$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t>$1205$ $1206$</w:t></w:r><w:bookmarkEnd w:id=""8""/></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc23$ = """><w:pPr><w:framePr w:w=""340"" w:h=""550"" w:hSpace=""181"" w:wrap=""around"" w:vAnchor=""page"" w:hAnchor=""page"" w:x=""642"" w:y=""5671""/><w:tabs><w:tab w:val=""left"" w:pos=""5387""/></w:tabs><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""16""/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""32""/></w:rPr><w:t>–</w:t></w:r></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc24$ = """><w:pPr><w:tabs><w:tab w:val=""left"" w:pos=""5387""/></w:tabs><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:bCs/><w:sz w:val=""24""/></w:rPr></w:pPr><w:bookmarkStart w:id=""9"" w:name=""ha4a""/><w:bookmarkEnd w:id=""9""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:bCs/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc25$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:bCs/><w:sz w:val=""24""/></w:rPr><w:tab/></w:r><w:bookmarkStart w:id=""10"" w:name=""ha4b""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:bCs/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doc26$ = "</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:bCs/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t>$1207$ $1208$</w:t></w:r><w:bookmarkEnd w:id=""10""/></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc27$ = """><w:pPr><w:tabs><w:tab w:val=""left"" w:pos=""5387""/></w:tabs><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:bCs/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr></w:pPr><w:bookmarkStart w:id=""11"" w:name=""ha5a""/><w:bookmarkEnd w:id=""11""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:bCs/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:tab/></w:r><w:bookmarkStart w:id=""12"" w:name=""ha5b""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:bCs/><w:vanish/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr><w:t>Fax $1216$:</w:t></w:r><w:bookmarkEnd w:id=""12""/></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' ' kommt 3 x vor:
' Public Const doc28$ = """><w:pPr><w:tabs><w:tab w:val=""left"" w:pos=""6946""/><w:tab w:val=""left"" w:pos=""9214""/></w:tabs><w:ind w:right=""-1""/><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:b/><w:sz w:val=""24""/><w:u w:val=""single""/></w:rPr></w:pPr></w:p><w:p w:rsidR=""00000000"" w:rsidRDefault="""
' Public Const doc29$ = """><w:pPr><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/><w:szCs w:val=""24""/></w:rPr></w:pPr><w:bookmarkStart w:id=""13"" w:name=""ha6a""/><w:bookmarkEnd w:id=""13""/><w:r><w:rPr><w:rFonts w:ascii=""Arial"" w:hAnsi=""Arial""/><w:sz w:val=""24""/></w:rPr><w:t>"
' Public Const doce$ = "</w:p><w:sectPr w:rsidR=""00000000""><w:headerReference w:type=""default"" r:id=""rId7""/><w:pgSz w:w=""11907"" w:h=""16840""/><w:pgMar w:top=""567"" w:right=""851"" w:bottom=""851"" w:left=""1418"" w:header=""720"" w:footer=""720"" w:gutter=""0""/><w:cols w:space=""720""/><w:titlePg/></w:sectPr></w:body></w:document>"
