# (Typ, kanonische Form, Formen oder Regex, Bemerkung, kind)  -- Reihenfolge = Anwendungsreihenfolge
# plain: Formen mit | getrennt; * = beliebige Endung; fuehrendes - = auch als Wortende in Zusammensetzungen; Endpunkt = Punkt optional
W = r"[\wäöüß]"
SEED = [
 ("Abkuerzung", "multiplen komplikationen", "mult.komp.|mult. komp.|multiple komplikationen|multiplen komplikationen", "Diabetes mellitus Typ 2 mit mult.Komp.", "plain"),
 ("Abkuerzung", "vena saphena magna", "v.s.m.|v.saphena magna|v. saphena magna|vena saphena magna", "", "plain"),
 ("Abkuerzung", "vena saphena parva", "v.s.p.|v.saphena parva|v. saphena parva|vena saphena parva", "", "plain"),
 ("Abkuerzung", "koronare herzkrankheit", "khk|khe|koronare herzkrankheit|koronare herzerkrankung", "KHK = KHE", "plain"),
 ("Abkuerzung", "periphere arterielle verschlusskrankheit", "pavk|periphere arterielle verschlusskrankheit", "", "plain"),
 ("Abkuerzung", "arterielle verschlusskrankheit", "avk", "", "plain"),
 ("Abkuerzung", "transitorische ischaemische attacke", "tia|transitorische ischämische attacke|transitorische ischaemische attacke", "", "plain"),
 ("Abkuerzung", "obstruktives schlafapnoesyndrom", "osas|obstruktives schlafapnoesyndrom", "", "plain"),
 ("Abkuerzung", "chronisch venoese insuffizienz", "cvi|chronisch venöse insuffizienz|chronisch venoese insuffizienz", "", "plain"),
 ("Abkuerzung", "nash", "nash|masld|nicht alkoholische steatohepatose|nichtalkoholische steatohepatose", "NASH = MASLD = nicht-alkoholische Steatohepatose", "plain"),
 ("Abkuerzung", "pco", r"(?<![\wäöüß])(?:pcos?|(?:polyz|polyc)\w*\.?\s*ovar\w*|syndrom\s+der\s+(?:polyz|polyc)\w*\s+ovarien)(?:\s*syndrom)?(?![\wäöüß])", "PCOS = PCO = polycyst./polyzystisches Ovar(-Syndrom) = Syndrom der polyzystischen Ovarien", "regex"),
 ("Abkuerzung", "polyneuropathie", "pnp", "PNP", "plain"),
 ("Abkuerzung", "lendenwirbelsaeule", "lws|lendenwirbelsäul*|lendenwirbelsaeul*", "LWS", "plain"),
 ("Abkuerzung", "halswirbelsaeule", "hws|halswirbelsäul*|halswirbelsaeul*", "HWS", "plain"),
 ("Abkuerzung", "brustwirbelsaeule", "bws|brustwirbelsäul*|brustwirbelsaeul*", "BWS", "plain"),
 ("Abkuerzung", "wirbelsaeule", "ws|wirbelsäul*|wirbelsaeul*", "WS", "plain"),
 ("Abkuerzung", "diabetes mellitus", "d.m.", "D.m. -> Diabetes mellitus", "plain"),
 ("Abkuerzung", "diabetes mellitus typ 2", "t2dm|t2d|diabetes mellitus, typ 2|diabetes mellitus typ 2|typ 2 diabetes mellitus|typ 2 diabetes", "T2Dm = T2D = D.m. Typ 2", "plain"),
 ("Abkuerzung", "diabetes mellitus typ 1", "t1dm|t1d|diabetes mellitus, typ 1|diabetes mellitus typ 1|typ 1 diabetes mellitus|typ 1 diabetes", "T1D = T1DM = D.m. Typ 1", "plain"),
 ("Abkuerzung", "insuffizienz", "-insuff.|insuff.", "-insuff. = -insuffizienz", "plain"),
 ("Abkuerzung", "hypercholesterinaemie", "hyperchol.|hypercholesterinämie|hypercholesterinaemie", "Hyperchol.", "plain"),
 ("Abkuerzung", "ueberfunktion", "-überfunktion|-überf.|-überfkt.|überfunktion|überf.|überfkt.", "-überfunktion = -überf. = -überfkt.", "plain"),
 ("Abkuerzung", "unterfunktion", "-unterfunktion|-unterf.|-unterfkt.|unterfunktion|unterf.|unterfkt.", "-unterfunktion = -unterf. = -unterfkt.", "plain"),
 ("Abkuerzung", "depression", "depr.|depression", "Depr.", "plain"),
 ("Abkuerzung", "thrombose", "-thromb.|thromb.|thrombose", "Thromb.", "plain"),
 ("Abkuerzung", "diabetisch", "diab.|diabet.|diabetisch*", "Diab. Polyneuropathie = Diabetische Polyneuropathie", "plain"),
 ("Abkuerzung", "rezidivierend", "rez.|rezidivierend*", "", "plain"),
 ("Abkuerzung", "chronisch", "chron.|chronisch*", "", "plain"),
 ("Abkuerzung", "arteriell", "art.|arteriell*", "art. Hypertonie = Arterielle Hypertonie", "plain"),
 ("Abkuerzung", "peripher", "periph.|peripher*", "", "plain"),
 ("Abkuerzung", "beginnend", "beg.|beginnend*", "", "plain"),
 ("Abkuerzung", "mikrozytaer", "mikrozyt.|mikrozytär*|mikrozytaer*", "", "plain"),
 ("Abkuerzung", "hirnzufuehrend", "hirnzuf.|hirnzuführend*|hirnzufuehrend*", "", "plain"),
 ("Abkuerzung", "hochgradig", "hochgr.|hochgradig*", "", "plain"),
 ("Abkuerzung", "intermittierend", "intermitt.|intermittierend*", "", "plain"),
 ("Abkuerzung", "vitamin", "vit.|vitamin", "Vit.B12-Mangel", "plain"),
 ("Abkuerzung", "gegen", "gg.|gegen", "Allergie gg. Hausstaub", "plain"),
 ("Rauschen", "", "nicht näher bezeichnet*|nicht naeher bezeichnet*|o.n.a.|a.n.k.|ohne nähere angabe|anderenorts nicht klassifiziert*", "wird beim Vergleich ignoriert", "plain"),
 # ---- Synonyme
 ("Synonym", "entzündung", "-infekt", "-infekt = -entzündung (nur in Zusammensetzungen, z. B. Harnwegsinfekt)", "plain"),
 ("Synonym", "karzinom", "-karzinom|-carcinom|-krebs|karzinom|carcinom|krebs", "-karzinom = -carcinom = -krebs", "plain"),
 ("Synonym", "prostatakarzinom", "prostataadenokarzinom|prostata adenokarzinom|prostatakarzinom|prostata karzinom", "Prostataadenokarzinom = Prostatakarzinom", "plain"),
 ("Synonym", "ulcus", "-ulcus|-ulkus|-geschwür|ulcus|ulkus|geschwür|geschwuer", "-ulcus = -geschwür", "plain"),
 ("Synonym", "hodgkin lymphom", r"(?<![\wäöüß])(?:hodgkin\s*(?:lymphom|krankheit|lymphogranulomatose)|(?:morbus|m\.)\s*hodgkin)(?![\wäöüß])", "Hodgkin-Lymphom = Hodgkin-Krankheit", "regex"),
 ("Synonym", "basedow krankheit", r"(?<![\wäöüß])(?:(?:morbus\s+|m\.\s*)?basedow(?:\s*krankheit)?)(?![\wäöüß])", "Basedow-Krankheit = Basedow = M. Basedow", "regex"),
 ("Synonym", "hyperthyreose", "schilddrüsen überfunktion|schilddrüsenüberfunktion|hyperthyreose", "Hyperthyreose = Schilddrüsenüberfunktion", "plain"),
 ("Synonym", "hypothyreose", "schilddrüsen unterfunktion|schilddrüsenunterfunktion|hypothyreose", "Hypothyreose = Schilddrüsenunterfunktion", "plain"),
 ("Synonym", "adipositas", "adipositas|übergewicht", "Adipositas = Übergewicht", "plain"),
 ("Synonym", "depression", "depression|verstimmung", "Depression = Verstimmung", "plain"),
 ("Synonym", "demenz", "demenz|vergesslichkeit", "Demenz = Vergesslichkeit", "plain"),
 ("Synonym", "glaukom", "glaukom|grüner star|grünen star", "Glaukom = grüner Star", "plain"),
 ("Synonym", "katarakt", "katarakt|grauer star|grauen star", "Katarakt = grauer Star", "plain"),
 ("Synonym", "arterielle hypertonie", r"(?<![\wäöüß])(?:arteriell\w*\s+)?(?:hypertonie|hypertonus)(?![\wäöüß])|(?<![\wäöüß])bluthochdruck(?![\wäöüß])", "Hypertonus = art. Hypertonie = Bluthochdruck", "regex"),
 ("Synonym", "sinusitis", r"(?<![\wäöüß])(?:sinusitis|(?:nasen)?nebenhöhlenentzündung)(?![\wäöüß])", "Sinusitis = (Nasen)nebenhöhlenentzündung", "regex"),
 ("Synonym", "nasenbluten", "nasenbluten|epistaxis", "Nasenbluten = Epistaxis", "plain"),
 ("Synonym", "fraktur", r"(?<![\wäöüß])(?:bruch|fraktur)(?![\wäöüß])|(?<=[\wäöüß])fraktur(?![\wäöüß])|(?<=[a-zäöüß])(?<!leisten)(?<!nabel)(?<!zwerchfell)(?<!narben)(?<!schenkel)(?<!hoden)(?<!hiatus)(?<!durch)(?<!ab)(?<!aus)(?<!um)(?<!zu)(?<!ein)(?<!vor)(?<!wund)bruch(?![\wäöüß])", "Bruch = Fraktur (Leisten-/Nabel-/Zwerchfell-/Narben-/Schenkel-/Hodenbruch ausgenommen)", "regex"),
]
